definitions:
  triggering:
    push: &events
      events:
        - push
        - pull_request
    scripts:
      - &buildFramework
        name: Build Framework
        script: |
          xcodebuild clean build \
            -scheme $XCODE_SCHEME \
            -destination "$DESTINATION" \
            -skipPackagePluginValidation
            
workflows:
  rrcomponentskit:
    name: BlocKit Workflow
    instance_type: mac_mini_m1
    environment:
      xcode: 14.2
      vars:
        XCODE_SCHEME: BlocKit
        DESTINATION: "platform=iOS Simulator,name=iPhone 14"
    triggering:
      <<: *events
    scripts: 
      - *buildFramework
